-- MySQL Script generated by MySQL Workbench
-- 04/22/15 17:26:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rm` DEFAULT CHARACTER SET latin1 ;
USE `rm` ;

-- -----------------------------------------------------
-- Table `rm`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`content` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `slug` CHAR(80) NULL DEFAULT NULL,
  `url` CHAR(80) NULL DEFAULT NULL,
  `TYPE` CHAR(80) NULL DEFAULT NULL,
  `title` VARCHAR(80) NULL DEFAULT NULL,
  `DATA` TEXT NULL DEFAULT NULL,
  `FILTER` CHAR(80) NULL DEFAULT NULL,
  `published` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  `category` CHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug` (`slug` ASC),
  UNIQUE INDEX `url` (`url` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rm`.`contentgenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`contentgenre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rm`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`genre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rm`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`movie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `director` VARCHAR(100) NULL DEFAULT NULL,
  `LENGTH` INT(11) NULL DEFAULT NULL,
  `YEAR` INT(11) NOT NULL DEFAULT '1900',
  `plot` TEXT NULL DEFAULT NULL,
  `image` VARCHAR(100) NULL DEFAULT NULL,
  `subtext` CHAR(3) NULL DEFAULT NULL,
  `speech` CHAR(3) NULL DEFAULT NULL,
  `quality` CHAR(3) NULL DEFAULT NULL,
  `format` CHAR(3) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `imdb` VARCHAR(255) NULL DEFAULT NULL,
  `youtube` VARCHAR(255) NULL DEFAULT NULL,
  `published` DATETIME NULL DEFAULT NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rm`.`movie2genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`movie2genre` (
  `idMovie` INT(11) NOT NULL,
  `idGenre` INT(11) NOT NULL,
  PRIMARY KEY (`idMovie`, `idGenre`),
  INDEX `idGenre` (`idGenre` ASC),
  CONSTRAINT `movie2genre_ibfk_1`
    FOREIGN KEY (`idMovie`)
    REFERENCES `rm`.`movie` (`id`),
  CONSTRAINT `movie2genre_ibfk_2`
    FOREIGN KEY (`idGenre`)
    REFERENCES `rm`.`genre` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rm`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acronym` CHAR(12) NOT NULL,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `password` CHAR(32) NULL DEFAULT NULL,
  `salt` CHAR(32) NULL DEFAULT NULL,
  `type` CHAR(80) NULL DEFAULT NULL,
  `email` CHAR(255) NULL DEFAULT NULL,
  `website` CHAR(255) NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `acronym` (`acronym` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;

USE `rm` ;

-- -----------------------------------------------------
-- Placeholder table for view `rm`.`vmovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm`.`vmovie` (`id` INT, `title` INT, `director` INT, `LENGTH` INT, `YEAR` INT, `plot` INT, `image` INT, `subtext` INT, `speech` INT, `quality` INT, `format` INT, `price` INT, `imdb` INT, `youtube` INT, `published` INT, `deleted` INT, `created` INT, `updated` INT, `genre` INT);

-- -----------------------------------------------------
-- View `rm`.`vmovie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rm`.`vmovie`;
USE `rm`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `rm`.`vmovie` AS select `m`.`id` AS `id`,`m`.`title` AS `title`,`m`.`director` AS `director`,`m`.`LENGTH` AS `LENGTH`,`m`.`YEAR` AS `YEAR`,`m`.`plot` AS `plot`,`m`.`image` AS `image`,`m`.`subtext` AS `subtext`,`m`.`speech` AS `speech`,`m`.`quality` AS `quality`,`m`.`format` AS `format`,`m`.`price` AS `price`,`m`.`imdb` AS `imdb`,`m`.`youtube` AS `youtube`,`m`.`published` AS `published`,`m`.`deleted` AS `deleted`,`m`.`created` AS `created`,`m`.`updated` AS `updated`,group_concat(`g`.`name` separator ',') AS `genre` from ((`rm`.`movie` `m` left join `rm`.`movie2genre` `m2g` on((`m`.`id` = `m2g`.`idMovie`))) left join `rm`.`genre` `g` on((`m2g`.`idGenre` = `g`.`id`))) group by `m`.`id`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
